import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs/promises";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outDir = "dist/team-docs-syncer";

const copyStaticPlugin = {
	name: "copy-static",
	setup(build) {
		build.onEnd(async () => {
			await fs.mkdir(outDir, { recursive: true });
			const copies = [];
			copies.push(
				fs.copyFile("manifest.json", path.join(outDir, "manifest.json"))
			);
			copies.push(
				fs
					.copyFile("styles.css", path.join(outDir, "styles.css"))
					.catch(() => {})
			);
			await Promise.all(copies);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outDir,
	minify: prod,
	plugins: [copyStaticPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
