import { AiProvider, ModelConfig } from "./AiProvider";

export const DEFAULT_MODELS: Record<AiProvider, ModelConfig[]> = {
	[AiProvider.OPENAI]: [
		{
			id: "gpt-5-nano",
			name: "GPT-5 Nano",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-5-mini",
			name: "GPT-5 Mini",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-5",
			name: "GPT-5",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-5-chat-latest",
			name: "GPT-5 Chat Latest",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "o4-mini",
			name: "o4 Mini",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-4.1-nano",
			name: "GPT-4.1 Nano",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-4.1-mini",
			name: "GPT-4.1 Mini",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-4.1",
			name: "GPT-4.1",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-4o-mini",
			name: "GPT-4o Mini",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-4o",
			name: "GPT-4o",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-4-turbo",
			name: "GPT-4 Turbo",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-4",
			name: "GPT-4",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gpt-3.5-turbo",
			name: "GPT-3.5 Turbo",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "chatgpt-4o-latest",
			name: "ChatGPT-4o Latest",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: false,
			supportsStreaming: false,
		},
		{
			id: "o1",
			name: "o1",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "o3-mini",
			name: "o3 Mini",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "o3",
			name: "o3",
			provider: AiProvider.OPENAI,
			maxTokens: 128000,
			supportsTools: true,
			supportsStreaming: true,
		},
	],
	[AiProvider.ANTHROPIC]: [
		{
			id: "claude-sonnet-4-20250514",
			name: "Claude Sonnet 4 (2025-05-14)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-opus-4-20250514",
			name: "Claude Opus 4 (2025-05-14)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-3-7-sonnet-20250219",
			name: "Claude 3.7 Sonnet (2025-02-19)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-3.5-haiku-20241022",
			name: "Claude 3.5 Haiku (2024-10-22)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-3.5-sonnet-20241022",
			name: "Claude 3.5 Sonnet (2024-10-22)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-3.5-sonnet-20240620",
			name: "Claude 3.5 Sonnet (2024-06-20)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-3-haiku-20240307",
			name: "Claude 3 Haiku (2024-03-07)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-3-sonnet-20240229",
			name: "Claude 3 Sonnet (2024-02-29)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "claude-3-opus-20240229",
			name: "Claude 3 Opus (2024-02-29)",
			provider: AiProvider.ANTHROPIC,
			maxTokens: 200000,
			supportsTools: true,
			supportsStreaming: true,
		},
	],
	[AiProvider.OLLAMA]: [],
	[AiProvider.GOOGLE]: [
		{
			id: "gemini-2.5-flash",
			name: "Gemini 2.5 Flash",
			provider: AiProvider.GOOGLE,
			maxTokens: 1000000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gemini-2.5-pro",
			name: "Gemini 2.5 Pro",
			provider: AiProvider.GOOGLE,
			maxTokens: 2000000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gemini-1.5-flash",
			name: "Gemini 1.5 Flash",
			provider: AiProvider.GOOGLE,
			maxTokens: 1000000,
			supportsTools: true,
			supportsStreaming: true,
		},
		{
			id: "gemini-1.5-pro",
			name: "Gemini 1.5 Pro",
			provider: AiProvider.GOOGLE,
			maxTokens: 2000000,
			supportsTools: true,
			supportsStreaming: true,
		},
	],
};
